{% set version = "0.1.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggcorrplot
  version: {{ version|replace("-", "_") }}

source:
  fn: ggcorrplot_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggcorrplot_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggcorrplot/ggcorrplot_{{ version }}.tar.gz
  sha256: 23c192c8c8e074d5835fe00196ce5d80f4b37990eed432e6ba5f3f3953db5d8b

build:
  noarch: generic
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2
    - r-reshape2
  run:
    - r-base
    - r-ggplot2
    - r-reshape2

test:
  commands:
    - $R -e "library('ggcorrplot')"  # [not win]
    - "\"%R%\" -e \"library('ggcorrplot')\""  # [win]

about:
  home: http://www.sthda.com
  license: GPL-2
  summary: The 'ggcorrplot' package can be used to visualize easily a correlation matrix using
    'ggplot2'. It provides a solution for reordering the correlation matrix and displays
    the significance level on the plot. It also includes a function for computing a
    matrix of correlation p-values.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
