travis:
  secure:
    BINSTAR_TOKEN: X/SwqqfEp80924cm3GueaBt5U9mvNUc38/O5Usol8HGuUqtZXi6OcFduAu6zCy6re4g0CObZWZHqZdg5j/q63Xb6VWbgczB5pxIE2CapH5BwYOV5rMSq2r2dIw84lzgrMihp+rRjnhP1GvjwxYSyCogEE0gic1zqEH9NzpksnirD5OkUklb8+kT1TPIVDlP40YSWZoRBvPoZni8C/R3glSocA6YsPFW8pruGC+esrgCpRO2OSBmOqBAxKDW3AlegGDzT9J5eZu6AvXUnzTREuJCaE/BbPLLemF44bcWQrLNewJBauS5w/tOVXiX/5VUSI4tRlYdFnRi/sO0E1Qybb4ntar/qNdWLx3o/AAt8TciLYPaxywUuJTkwmEn3hTh9pXo8bSsb2uWzhWlnNSSOy4BVET/JhCVjqoVZiZr/U3EPX45gWjNFnM2LmLEKJXz5NSthXoPtgrRrFQ/e+m9T/s3wcnMNuvlpsszDFkmQi0kLqM/3xRR1R8su8ZWjyCnUaFBfN5446Q12VpfknagDCZAvp/5o1MaYkObGKSNl1UZij9jBf/76xRQibkzRJm1vU6YtJQyExj6H54h9XRIgbDPjcnRgiHt+ygw3pDKX6SYsJSuM784j9nituzpg6LTtJbtp8bGhauzIkai9p0kXi3cN0az1rlBsPujUMQUQzic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
