travis:
  secure:
    BINSTAR_TOKEN: jDSKR9+ptjLO2HgW9xFIwvD0pPqSXJKk5aAtT0Fd0ur826CISaGc9t35KJ2SIPjpHyrQK/TR1HddmCrm8D+SPD4ByjyJ0LOL+l9JgKftLM2iTKRcAaabhfqBEb73hYHUjjyqbnPvM7/uOhwgxaO7xxbYaqXAYTdEtI1NZd8GmbdxNEjDICIZW2/XiR390xLaFeltLalZffgZx/ggjbHk4mjwdwN1gqdu+jh7E9AmT7mJsMGYcWObObb05hCFbm4fUe7CbgHZQbcns2qXWt7kN5Rn1I5p7c9FXEjOFA2z7WSloK2bcR/ATO4uxKGsz2pJIyL7yfwp6HXal6pF6TU9lhdHgZu7iWtgPXj9b81HMG77lEzoRiJiyWyH6HZorzsdcUQnSwrykBso/yKjrvTvBflSY77pqjbT++n7VQNkxR1/V0SvYC3++RxX5e+NvEnEe80XXyecZ6PGmHOs0ImWB1t3YpN5aZpBNxv+ZopIWd+4RSrBGe4qWOGcuKFGsOAh9rXKdbK3WagNXNPp3MCye8aSCpxOd+ewnxmL0s1nlEu2NkPzDGM9w5P2/lPYl883Fh9RN3N2EnUHkD61yqrhkE4s4q5gzI1yWGMlOppQ8HRY3jda1bq1cQ25XZlLVOIwGzBgaNVkJlln8NfGpyK+NpUm/Otq4moWRtHa0ubw8N0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
