travis:
  secure:
    BINSTAR_TOKEN: Lz0zRlwxP6MXvDh9xMVng4viQ3ujcoOTO91H5VItBW9Q7se1TL99esaQ5jgebxt+Z2u8xlsSWXxBZXW8JHZzrMRNeI+WkZ5XX71hhxoOqsq/fhiphtFsYUpfbc4JgL7bx+aBZJNFPdxZCFEr63usPw564BktfxCfSZopiLgiRg8pZGzn7QySbL3Ng3PVFB6hpaj4ZWZTTqFKwjEFbC45Va/2Q9rzaxi4pjJ1B0L1iYEzkz37J4I9nWq3+icMk6x+zCtyu6HF9ScNERFLx7sJ412gLx87CdSUBoDliZTvbHmbwqwfRr26/Rs41NwXAV1kD+Po94gIvMrrdFWMAxi/35V74xVGLZ06SmWotUoJZzPd66vdJoUAO7PFLsSpEPG4fFWV/Wm7qOB2t6NPRpT4aQbgOseRTfF8y6IudK6yfagk+LcToE0gzyi2nBzT5UaZ2mZJuwJ/9T5rjIvcf35e/RgQBW+Ih9pDUAyn76fo0TmpKYJ224NlPMTODAxbsXVveLkz4X9HFBEG0YDYluG+h//7o2xhhzG1TUAPrhFIu7DSCpu0nOhgbxZJB7AEVxV2FAVECMe0sT1blOL2GINotc2p0KzP8xOPGaH2OjKtLWTGff6h3g2vpi3ldQekdZOwGFh7Uhz10w0aYDGtQvJcdRVT4FSzBZW7NxeowCApuJA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
